const MAX_DB = -10
const MIN_DB = -140
const SMOOTHING_TIME_CONSTANT = .91
const FFT_SIZE = 4096
const START_GAIN = .8

export {
  MAX_DB,
  MIN_DB,
  SMOOTHING_TIME_CONSTANT,
  FFT_SIZE,
  START_GAIN
}
