const FILE_ERROR_MODAL_ID = 'fileErrorModal'
const TRACK_INFO_MODAL_ID = 'trackInfoModal'
const DELETE_TRACK_MODAL_ID = 'deleteTrackModal'
const APP_INFO_MODAL_ID = 'appInfoModal'

const MODAL_IDS = [
	FILE_ERROR_MODAL_ID,
	TRACK_INFO_MODAL_ID,
	DELETE_TRACK_MODAL_ID,
	APP_INFO_MODAL_ID
]

export {
	FILE_ERROR_MODAL_ID,
	TRACK_INFO_MODAL_ID,
	DELETE_TRACK_MODAL_ID,
	APP_INFO_MODAL_ID,
	MODAL_IDS
}
