const PARTICLE_MENU_ID = 'particleMenu'
const PLAYLIST_MENU_ID = 'trackMenu'

const SLIDER_MENU_IDS = [
	PARTICLE_MENU_ID,
	PLAYLIST_MENU_ID
]

export { PARTICLE_MENU_ID, PLAYLIST_MENU_ID, SLIDER_MENU_IDS }
